name: Deploy to EKS

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Login to ECR
      run: |
        aws ecr get-login-password --region us-east-1 | \
        docker login --username AWS --password-stdin 187249972779.dkr.ecr.us-east-1.amazonaws.com

    - name: Build and Push Docker Image
      run: |
        docker build -t httpd-image:latest venkat/Dockerfile
        docker tag httpd-image:latest 187249972779.dkr.ecr.us-east-1.amazonaws.com/my-ecr-repo/httpd-image:latest
        docker push 187249972779.dkr.ecr.us-east-1.amazonaws.com/my-ecr-repo/httpd-image:latest

    - name: Update kubeconfig
      run: |
        aws eks update-kubeconfig --region us-east-1 --name EKS_CLUSTER_NAME

    - name: Deploy to EKS
      run: |
        kubectl apply -f kubernetes/deployment.yaml
